name: Customer Docker Images

on:
  push:
    branches:
     - 'customer-*'
  pull_request:
    branches:
     - 'customer-*'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_CHECKOUT }}

      - uses: depot/setup-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set Short Commit Hash
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build (optionally publish) PeerDB Customer Image
        uses: depot/build-push-action@v1
        with:
          token: ${{ secrets.DEPOT_TOKEN }}
          context: .
          file: stacks/nexus.Dockerfile
          push: ${{ startsWith(github.ref, 'refs/heads/customer-') }}
          tags: |
            ghcr.io/peerdb-io/peerdb-server:customer-${{ steps.vars.outputs.sha_short }}

      - name: Build (optionally publish) Flow API Customer Image
        uses: depot/build-push-action@v1
        with:
          token: ${{ secrets.DEPOT_TOKEN }}
          context: .
          file: stacks/flow-api.Dockerfile
          push: ${{ startsWith(github.ref, 'refs/heads/customer-') }}
          tags: |
            ghcr.io/peerdb-io/flow-api:customer-${{ steps.vars.outputs.sha_short }}

      - name: Build (optionally publish) Flow Worker Customer Image
        uses: depot/build-push-action@v1
        with:
          token: ${{ secrets.DEPOT_TOKEN }}
          context: .
          file: stacks/flow-worker.Dockerfile
          push: ${{ startsWith(github.ref, 'refs/heads/customer-') }}
          tags: |
            ghcr.io/peerdb-io/flow-worker:customer-${{ steps.vars.outputs.sha_short }}

      - name: Build (optionally publish) Flow Snapshot Worker Customer Image
        uses: depot/build-push-action@v1
        with:
          token: ${{ secrets.DEPOT_TOKEN }}
          context: .
          file: stacks/flow-snapshot-worker.Dockerfile
          push: ${{ startsWith(github.ref, 'refs/heads/customer-') }}
          tags: |
            ghcr.io/peerdb-io/flow-snapshot-worker:customer-${{ steps.vars.outputs.sha_short }}